### ISSUE TITLE
Initial admin view

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ncdot-road-safety#4]
we'll need to know the logged-in user's role to know if access to Admin view is granted.

we think we should have a fixed set of available annotations ("guardrail", "tree", etc)

for now, add ability to add/remove/edit available annotations for annotators to use.

**Comment by hyi** [comment]
@mbwatson I believe all the functionalities you mentioned in this issue have been implemented in the Django admin view panel. Each user can be assigned with an admin role from the admin panel in order to login to the admin panel with ```/admin``` URL. Any admin user can add/remove/edit new or available annotations for annotators to use from the admin panel as well at run time. So I am closing this issue for now.
